### ISSUE TITLE
Enabling publishing ble2uart.zip to GH Release

### ISSUE THREAD

**Issue by Ircama** [pvvx/ADV_BLE2UART#26]
@pvvx I merged a [contribution to add some GitHub Actions to this repository](https://github.com/pvvx/ADV_BLE2UART/commit/cc1fe4cd7661fe5e5e48a3b03deaddb7de11f858)  and they seem to run, but [the workflow that builds the firmware](https://github.com/pvvx/ADV_BLE2UART/blob/master/.github/workflows/build.yml) needs to have read and write permissions in the repository to upload the generated *ble2uart.zip* archive to the [GitHub Release folder](https://github.com/pvvx/ADV_BLE2UART/releases/latest).

I'd ask to follow these steps:

- Go to https://github.com/pvvx/ADV_BLE2UART/settings/actions
- In the left sidebar, click *Actions*, then click *General*.
- Go down to the "Workflow permissions" section.
- Select "Read and write permissions".
- Press SAVE.
- Go to https://github.com/pvvx/ADV_BLE2UART/actions/runs/10395869198
- Press "Re-run jobs" (rerun failed jobs). The total duration of the build job takes 5 minutes.

As a usage remark, after a new contribution, to run again the GH Actions you need to push tags. Adding below some notes.

-------------------
Push all changes:

```shell
git commit -a
git push
```

_After pushing the last commit_, add a local tag (shall be added AFTER the commit that needs to rebuild the exe):

```shell
git tag # list local tags
git tag v1.0.0
```

Push this tag to the origin, which starts the rebuild workflow (GitHub Action):

```shell
git push origin v1.0.0
```

**Comment by pvvx** [comment]
![image](https://github.com/user-attachments/assets/cded076b-e032-40a5-9d0c-9949372562c1)

**Comment by Ircama** [comment]
Thank you
